export enum Icons {
    remove = 'remove',
    add = 'add',
    link = 'link',
    liquidityPool = 'waves',
    market = 'equalizer',
    volume = 'equalizer',
    mining = 'whatshot',
    staking = 'verified_user',
    swap = 'swap_horiz',
    provide = 'control_point_duplicate',
    wallet = 'account_balance_wallet',
    bug = 'bug_report',
    star = 'star',
    delete = 'delete',
    lock = 'lock',
    lightMode = 'brightness_7',
    darkMoke = 'brightness_3',
    checkCircle = 'check_circle',
    check = 'check_circle',
    close = 'close',
    tokens = 'toll',
    rewards = 'star',
    help = 'help'
}
