export enum TransactionSummaryTypes {
  SrcToSrcSwap = 1,
  SrcToCrsSwap = 2,
  CrsToSrcSwap = 3,
  AddLiquidity = 4,
  RemoveLiquidity = 5,
  StartStaking = 6,
  StopStaking = 7,
  StartMining = 8,
  StopMining = 9,
  CollectLiquidityRewards = 10,
  CollectStakingRewards = 11,
  CollectMiningRewards = 12,
  CreateLiquidityPool = 13,
  CreateMarket = 14,
  SetPendingOwnership = 15,
  ClaimPendingOwnership = 16,
  CreateVaultCertificate = 17,
  RedeemVaultCertificate = 18,
  RevokeVaultCertificate = 19,
  Distribution = 20,
  ChangeMarketPermission = 21,
  EnableMining = 22,
  RewardMiningPool = 23,
  Nomination = 24,
  Approval = 25,
  Transfer = 26
}
